import 'dotenv/config';

export default ({ config }) => ({
  ...config,
  extra: {
    EXPO_PUBLIC_APP_NAME: process.env.EXPO_PUBLIC_APP_NAME,
    EXPO_PUBLIC_API_URL: process.env.EXPO_PUBLIC_API_URL,
    EXPO_PUBLIC_SUPABASE_URL: process.env.EXPO_PUBLIC_SUPABASE_URL,
    EXPO_PUBLIC_SUPABASE_ANON_KEY: process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY,
    EXPO_PUBLIC_SUPABASE_SERVICE_ROLE_KEY: process.env.EXPO_PUBLIC_SUPABASE_SERVICE_ROLE_KEY,

    EXPO_PUBLIC_MESSAGES_SOURCE: process.env.EXPO_PUBLIC_MESSAGES_SOURCE,
    EXPO_PUBLIC_ALLOW_UNVERIFIED: process.env.EXPO_PUBLIC_ALLOW_UNVERIFIED,
    EXPO_PUBLIC_DEV_BYPASS: process.env.EXPO_PUBLIC_DEV_BYPASS,

    EXPO_PUBLIC_API_TIMEOUT: process.env.EXPO_PUBLIC_API_TIMEOUT,
    EXPO_PUBLIC_API_EXTENDED_TIMEOUT: process.env.EXPO_PUBLIC_API_EXTENDED_TIMEOUT,
    EXPO_PUBLIC_API_MAX_RETRIES: process.env.EXPO_PUBLIC_API_MAX_RETRIES,

    EXPO_PUBLIC_FACEBOOK_APP_ID: process.env.EXPO_PUBLIC_FACEBOOK_APP_ID,
    EXPO_PUBLIC_FACEBOOK_APP_SECRET: process.env.EXPO_PUBLIC_FACEBOOK_APP_SECRET,

    REACT_APP_GOOGLE_MAPS_API_KEY: process.env.REACT_APP_GOOGLE_MAPS_API_KEY,
    ENV: process.env.ENV,
    NODE_ENV: process.env.NODE_ENV,
  },
});